name: Publish Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Helm Package
        run: echo "PACKAGE_PATH=$(helm package . | awk '{print $NF}')" >> $GITHUB_ENV

      - name: Push to GHCR
        run: |
          helm registry login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          helm push ${{ env.PACKAGE_PATH }} oci://ghcr.io/${{ github.repository_owner }}

      - name: GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.PACKAGE_PATH }}
          generate_release_notes: true
